{
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "kubenamespace", "label": "Kubernetes namespace", "query": "${VAR_KUBENAMESPACE}" },
   { "name": "latency", "label": "Latency percentile", "query": "0.5,0.9,0.95,0.999" },
   { "name": "service", "label": "Service base name", "query": "${VAR_SERVICE}" },
   { "name": "vhost", "label": "RMQ virtual host", "query": "${VAR_VHOST}" },
   { "name": "rmq_prefix", "label": "RMQ prefix", "query": "${VAR_RMQ_PREFIX}" },
   { "name": "rmq_env", "label": "RMQ environment", "query": "${VAR_RMQ_ENV}" }
  ]
 },
 "panels": [
  { "title": "Kube resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$kubenamespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=\"$kubenamespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "timeseries",
   "description": "CPU requests by deployment.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$kubenamespace\", container=~\"$service-?.*\"}) by (container) / count(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$kubenamespace\", container=~\"$service-?.*\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "RAM requests",
   "type": "timeseries",
   "description": "RAM requests by deployment.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$kubenamespace\", container=~\"$service-?.*\"}) by (container) / count(1, kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$kubenamespace\", container=~\"$service-?.*\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU limits",
   "type": "timeseries",
   "description": "CPU limits by deployment.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$kubenamespace\", container=~\"$service-?.*\"}) by (container) / count(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$kubenamespace\", container=~\"$service-?.*\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "RAM limits",
   "type": "timeseries",
   "description": "RAM limits by deployment.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$kubenamespace\", container=~\"$service-?.*\"}) by (container) / count(kube_pod_container_resource_limits{resource=\"memory\", namespace=\"$kubenamespace\", container=~\"$service-?.*\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Intra services API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Latency $latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${latency:raw}, sum(rate(intra_connector_request_latency_sec_bucket{namespace=\"$kubenamespace\"}[5m])) by (le, client_name, path, host))",
     "legendFormat": "{{client_name}} {{host}}{{path}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(intra_connector_request_count_total{namespace=\"$kubenamespace\"})[$__rate_interval]) by (method, path, status)",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(intra_connector_request_count_total{namespace=\"$kubenamespace\"})[$__rate_interval]) by (client_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Produce rate (queues)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_published_total{queue=~\"$rmq_prefix.*\", vhost=~\"$rmq_env.*\"}[10m])",
     "legendFormat": "{{queue}} ({{vhost}})"
    }
   ]
  },
  {
   "title": "Consume rate (queues)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_delivered_total{queue=~\"$rmq_prefix.*\", vhost=~\"$rmq_env.*\"}[10m])",
     "legendFormat": "{{queue}} ({{vhost}})"
    }
   ]
  },
  {
   "title": "Produce rate (vhost)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_published_total{vhost=\"$vhost\"}[10m])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Consume rate (vhost)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_queue_messages_delivered_total{vhost=\"$vhost\"}[10m])) by (queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages total (queues)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=~\"$rmq_prefix.*\", vhost=~\"$rmq_env.*\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages total (vhost)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{vhost=\"$vhost\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Consumers (queues)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_consumers{queue=~\"$rmq_prefix.*\", vhost=~\"$rmq_env.*\"}) by (queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumers (vhost)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_consumers{vhost=\"$vhost\"}) by (queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections (vhost)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "sum(rabbitmq_connection_channels{vhost=\"$vhost\"}) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(database_request_count{namespace=\"$kubenamespace\"})) by (app_kubernetes_io_instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(database_request_error_count{namespace=\"$kubenamespace\"})) by (app_kubernetes_io_instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency $latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${latency:raw}, sum(rate(database_request_time_bucket{namespace=\"$kubenamespace\"}[5m])) by (le, app_kubernetes_io_instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection acquire rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "sum(rate(connection_acquired_count{namespace=\"$kubenamespace\"})) by (app_kubernetes_io_instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection release rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "sum(rate(connection_released_count{namespace=\"$kubenamespace\"})) by (app_kubernetes_io_instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection acquire errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "targets": [
    {
     "expr": "sum(rate(connection_acquire_error_count{namespace=\"$kubenamespace\"})) by (app_kubernetes_io_instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection acquire latency $latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(${latency:raw}, sum(rate(connection_acquire_time_bucket{namespace=\"$kubenamespace\"}[5m])) by (le, app_kubernetes_io_instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(requests_total{namespace=\"$kubenamespace\", path=~\"/api/v.*|/srv/.*\"})[$__rate_interval]) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(status_codes_total{namespace=\"$kubenamespace\", path=~\"/api/v.*|/srv/.*\"})[$__rate_interval]) by (method, path, status_code) ",
     "legendFormat": "{{method}} {{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "500",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "targets": [
    {
     "expr": "sum(rate(status_codes_total{namespace=\"$kubenamespace\", path=~\"/api/v.*|/srv/.*\", status_code=~\"5..\"})[$__rate_interval]) by (path, status_code)",
     "legendFormat": "{{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "400",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "targets": [
    {
     "expr": "sum(rate(status_codes_total{namespace=\"$kubenamespace\", path=~\"/api/v.*|/srv/.*\", status_code=~\"4..\"})[$__rate_interval]) by (path, status_code)",
     "legendFormat": "{{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Business",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 },
   "collapsed": true
  }
 ]
}