FROM python:3.12.4-slim-bookworm

ENV VERSION="local"

COPY .ci-cd/pip.conf /etc/pip.conf

WORKDIR /code

COPY requirements.txt /code/
COPY requirements-test.txt /code/

RUN echo \
    "deb http://mirror.yandex.ru/debian bookworm main\n" \
    "deb http://mirror.yandex.ru/debian-security bookworm-security main\n" \
    "deb http://mirror.yandex.ru/debian bookworm-updates main\n" > /etc/apt/sources.list \
    && apt-get update && apt-get install -y git gcc curl \
    && pip3 install -U pip wheel && pip3 install -r requirements.txt -r requirements-test.txt

COPY . /code

EXPOSE 8000
