"""
Create base tables
"""

from yoyo import step

__depends__ = {}

steps = [
    step(
        """
        CREATE TABLE IF NOT EXISTS users (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name text NOT NULL,
            --TODO add fields
        );
        CREATE INDEX ON users (name text_pattern_ops);
        """,
        """
        DROP TABLE IF EXISTS users;
        """
    ),
    step(
        """
        CREATE TABLE IF NOT EXISTS organization (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name BIGINT NOT NULL,
            organization_type INT NOT NULL,
            --TODO add fields
        );
        CREATE INDEX ON organization (name text_pattern_ops);
        """,
        """
        DROP TABLE IF EXISTS organization;
        """
    ),
    step(
        """
        CREATE TABLE IF NOT EXISTS wallet (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            user_id BIGINT REFERENCES users(id) NOT NULL,
            address text NOT NULL,
            private text NOT NULL
        );
        """,
        """
        DROP TABLE IF EXISTS wallet;
        """
    )
]
