"""
Create all base tables
"""

from yoyo import step

__depends__ = {}

steps = [
    step(
        apply="""
            CREATE TABLE IF NOT EXISTS city (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                name text NOT NULL
            );
        """,
        rollback="""
            DROP TABLE IF EXISTS city;
        """,
    ),
    step(
        apply="""
            CREATE TABLE IF NOT EXISTS feedback (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                feedback text NOT NULL,
                date date NOT NULL,
                
                author_id bigint NOT NULL,
                job_id bigint NOT NULL
            );
        """,
        rollback="""
            DROP TABLE IF EXISTS feedback;
        """,
    ),
    step(
        apply="""
            CREATE TABLE IF NOT EXISTS user_info (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                login text NOT NULL UNIQUE,
                first_name text NOT NULL,
                last_name text NOT NULL,
                third_name text,
                about text,
                date_of_birth date,
                
                city_id bigint 
            );
        """,
        rollback="""
            DROP TABLE IF EXISTS user_info;
        """,
    ),
    step(
        apply="""
            CREATE TABLE IF NOT EXISTS job (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                name text NOT NULL
            );
        """,
        rollback="""
            DROP TABLE IF EXISTS job;
        """,
    ),
    step(
        apply="""
            CREATE TABLE IF NOT EXISTS user_job (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                
                user_info_id bigint NOT NULL,
                job_id bigint NOT NULL
            );
        """,
        rollback="""
            DROP TABLE IF EXISTS user_job;
        """,
    ),
    step(
        apply="""
            CREATE TABLE IF NOT EXISTS user_job_position (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                position text NOT NULL,
                started_at date NOT NULL,
                ended_at date,
                
                user_job_id bigint NOT NULL
            );
        """,
        rollback="""
            DROP TABLE IF EXISTS user_job_position;
        """,
    ),
    step(
        apply="""
            CREATE TABLE IF NOT EXISTS skill (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    
                name text NOT NULL
            );
        """,
        rollback="""
            DROP TABLE IF EXISTS skill;
        """,
    ),
    step(
        apply="""
            CREATE TABLE IF NOT EXISTS user_skill (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                
                user_info_id bigint NOT NULL,
                skill_id bigint NOT NULL 
            );
        """,
        rollback="""
            DROP TABLE IF EXISTS user_skill;
        """,
    ),
    step(
        apply="""
            CREATE TABLE IF NOT EXISTS user_study_position (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                position text NOT NULL,
                started_at date NOT NULL,
                ended_at date,   
    
                user_study_id bigint NOT NULL
            );
        """,
        rollback="""
            DROP TABLE IF EXISTS user_study_position;
        """,
    ),
    step(
        apply="""
            CREATE TABLE IF NOT EXISTS user_study (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                name text NOT NULL,
    
                user_info_id bigint NOT NULL
            );
        """,
        rollback="""
            DROP TABLE IF EXISTS user_study;
        """,
    ),
    step(
        # TODO: user - entity for login in system, need to create with AUTH and link them and user_info base entity
        """
        CREATE TABLE IF NOT EXISTS wallet (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            address text NOT NULL,
            private text NOT NULL
        );
        """,
        """
        DROP TABLE IF EXISTS wallet;
        """
    )
]
